version: '3.8'

services:
  face-attendance-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face-attendance-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped
    volumes:
      - .:/app

# Removed networks and volumes since we don't need them with single service